name:                prover
version:             0.1.0.0
github:              "avan1235/prover"
license:             BSD3
author:              "Maciej Procyk"
maintainer:          "m.procyk@student.uw.edu.pl"
copyright:           "2022 Maciej Procyk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/prover#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck >= 2.14 && < 2.15
- parsec >= 3.1 && < 3.2
- random >= 1.2 && < 1.3
- mtl >= 2.2 && < 2.3
- containers >= 0.6 && < 0.7
- transformers >= 0.5 && < 0.6

library:
  source-dirs: src

executables:
  prover-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prover

